name: Mermaid Grotto
favicon: null
layout_spectrum: 0.63389
typography_spectrum: 0.67311
title: 'Mermaid Grotto: Hidden Treasures'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#00c0c2'
    - '#ffffff'
    - '#66a8da'
    - '#bb92ee'
  brandStrength: 0.7746190049219877
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
