name: Mermaid Grotto
favicon: null
layout_spectrum: 0.5319965626113117
typography_spectrum: 0.018868632847443223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7746190049219877
  lightness: 0.4981369460001588
  saturation: 0.42064356920309365
  rhythmicContrast: 0.47603609785437584
purpose: []
